Add business rules to the create feed markdown
usdot-jpo-ode/jpo-wzdx pull request #116
Opened 2020-07-10 15:23 UTC by wesleyalforddot

This PR adds current business rules to the create feed markdown. This is guidance for how to implement the specification to ensure standardization from data produces and to facilitate data consumer usage.

2020-09-15 18:28 UTC, j-d-b requested changes
I'd highly recommend renaming all the png images to more clearly represent what they are. Out of context, `scenario1.png` has no meaning. I think you could just change them to what the header name is in `example-work-zone-scenarios.md` file. That is, `scenario1.png` renamed to `simple-work-zone-scenario.png`.

2020-09-15 19:17 UTC, j-d-b commented on create-feed/README.md
> +5. The features array represents a list of one or more road events. Each object in this array has three properties: type, properties, and geometry. Type will always be feature. Properties will provid
Again this is a helpful text description of what the schema says but it is not a business rule, it is required by the schema.

2020-09-15 19:17 UTC, j-d-b commented on create-feed/README.md
> +6. A mobile work zone should consider the update frequency of the WZDx data feed found in the metadata datafeed_frequency_update field. A mobile work zone should define the start and end of the work
This needs to be updated for v3.0 (metadata is gone)

2020-09-15 19:17 UTC, j-d-b commented on create-feed/README.md
> +7. A cascading multilane closure should consider the speed of vehicles traveling through the work zone. If the distance between lane closure would not allow for a significant period of travel in a to
Where did this come from? Can you link an issue or discussion?

2020-09-18 13:51 UTC, wesleyalforddot commented on create-feed/README.md
> +7. A cascading multilane closure should consider the speed of vehicles traveling through the work zone. If the distance between lane closure would not allow for a significant period of travel in a to
This was made in reference to scenario 6 from the annotated examples here [https://github.com/usdot-jpo-ode/jpo-wzdx/discussions/131](https://github.com/usdot-jpo-ode/jpo-wzdx/discussions/131). If you have suggested wording or don't think this rules is reasonable let me know and I can remove it.

2020-09-21 14:36 UTC, merged

2020-09-21 14:38 UTC, j-d-b commented
@wesleyalforddot this was never approved. Please wait until you have approved reviewers before merging PRs. All PRs should have at least one approved review from a maintainer/co-chair, as per the charter.