Object Model Refactoring and Repository Organization
usdot-jpo-ode/jpo-wzdx pull request #138
Opened 2020-11-06 04:39 UTC by j-d-b

This resolves #112 and implements the switch from a relational model to an object model.

Many changes to the specification files, including the schema, were made for the PR, but all changes are cosmetic and do not change the content or structure of a WZDx GeoJSON document.

## Major changes
It is imperative to review the actual changes to the files to cover all the changes that were made, though at a high level, the following major changes were made:

- Removed the `data-tables` directory and files
- Created an `objects` directory to house all data entities (objects) and within it a markdown file for each object to replace the `data-tables. Most of the entities line up directly from table to object (e.g. `lanes` table to `Lane` object), but there are some objects that did not exist as a table (e.g. for the `WZDxFeed` root object and `RoadEventFeature` `RoadEvent` container). For the latter, the schema already defined these objects. The `objects` directory contents now directly matches up with the object definitions in the `definitions` section of the schema.
- Renamed all object and enumerated type definitions in the schema from snake_case to PascalCase, to better follow object/type naming conventions
- Renamed all enumerated type files to follow the PascalCase naming convention
- Used the same formatting and section names within all objects and enumerated types

## Remaining work
The last item remaining before this can move out of draft status is removing the ERD and replacing it with an object diagram (and updating the READMEs it is referenced in). If @chuehlien or @DeraldDudley could do this, again with drawio, that would be great. If not, let me know.

2020-11-09 18:33 UTC, chuehlien requested changes
Great work!!! This refactor makes the GeoJSON structure of the feed a lot clearer.

Added some minor comments for typos/file renaming. Can approve the PR once those are addressed.

2020-11-09 18:33 UTC, chuehlien commented on spec-content/objects/RoadEvent.md
> +The `RoadEvent` object contains information that describes where, when, and what activity is taking place along a road segment. This specification currently accommodates `work-zone` and `detour` type
Update link and link text from `event_type.md` to `EventType.md`

2020-11-09 18:33 UTC, chuehlien commented on spec-content/objects/RoadEvent.md
> +`relationship` | [Relationship](/spec-content/objects/Relationship.md) | Identifies both sequential and hierarchical relationships between the roa events and other entities. For example, a relationsh
`roa` -> `road`

2020-11-09 18:33 UTC, chuehlien commented on spec-content/objects/RoadEvent.md
> +`restrictions` | Array; \[[RoadRestriction](/spec-content/enumerated-types/RoadRestriction.md)\] | Zero or more road restrictions applying to the work zone road segment associated with the work zone
Since `restrictions` is of the type "Array" (and not String), we can remove the `delimited by semicolons` part of the description.

2020-11-09 18:33 UTC, chuehlien commented on spec-content/objects/RoadEventFeature.md
> +`features` | [WZDx Feed](/spec-content/objects/wzdx_feed.md)
`wzdx_feed.md` -> `WZDxFeed.md`

2020-11-09 18:33 UTC, chuehlien commented on spec-content/objects/RoadEventFeedInfo.md
> +`data_sources` | Array; \[[RoadEventDataSource](/spec-content/objects/RoadEventDataSource.md)\] | A list specific data sources for the road event data in the feed. | Required | Length of array must b
`A list specific` -> `A list of specific`

2020-11-09 23:46 UTC, j-d-b commented on README.md
> +    - [**Objects**](/spec-content/data-tables)
All three resolved.

2020-11-09 23:53 UTC, j-d-b commented on spec-content/objects/relationship.md
> +# Relationship Object
Fixed and oddly this was something weird with my local version as it shows capitalized locally for me. Had to change via the GitHub web UI.

2020-11-09 23:56 UTC, j-d-b commented on create-feed/README.md
> +- The [LaneRestriction](/spec-content/objects/LaneRestriction.md) object describes restrictions for identified lanes.
Same here.

2020-11-09 23:56 UTC, j-d-b commented on spec-content/enumerated-types/derived-from-its-standards/direction.md
>  The direction for a roadway is based on the standard naming for US roadways and indicates the direction the traffic flow regardless of the real heading angle of the roadway.
Same here.

2020-11-09 23:58 UTC, j-d-b commented on create-feed/schemas/wzdx_v3.0_feed.json
> +          "description": "The GeoJSON object type—must be 'Feature'",
it is an em-dash but likely that didn't render correctly. I will change to a semi-colon.

2020-11-10 00:14 UTC, j-d-b commented on spec-content/objects/RoadEvent.md
> +`restrictions` | Array; \[[RoadRestriction](/spec-content/enumerated-types/RoadRestriction.md)\] | Zero or more road restrictions applying to the work zone road segment associated with the work zone
Very good note.

2020-11-10 00:18 UTC, j-d-b reviewed
> Added some minor comments for typos/file renaming. Can approve the PR once those are addressed.

Thank you for reviewing. I made all the changes/fixes you noted. 

Before we can merge we need to change the ERD into an object diagram. @chuehlien are you able to do this? I can review if so.

2020-11-10 18:31 UTC, chuehlien commented on spec-content/objects/relationship.md
> +# Relationship Object
Yea, I've seen this happen with other repo too where upper/lowercase file name changes don't always get tracked properly by Git. Glad you were able to figure out a fix!

2020-11-10 18:37 UTC, chuehlien commented on spec-content/objects/RoadEvent.md
> +The `RoadEvent` object contains information that describes where, when, and what activity is taking place along a road segment. This specification currently accommodates `work-zone` and `detour` type
The link text has been fixed but the link still needs to be fixed.

2020-11-10 18:39 UTC, chuehlien commented on create-feed/README.md
> +- The [LaneRestriction](/spec-content/objects/LaneRestriction.md) object describes restrictions for identified lanes.
Very minor, but would be good to change `TypesOfWork` -> `TypeOfWork` to be consistent (line 28).

2020-11-10 18:52 UTC, j-d-b commented on create-feed/README.md
> +- The [LaneRestriction](/spec-content/objects/LaneRestriction.md) object describes restrictions for identified lanes.
Agree for sure. Not that minor, it's wrong and needs to be corrected. I seems to always miss these things.

Also, if it it easier for you, you can make any of these trivial changes that don't necessitate discussion yourself directly on the branch rather than going through the comment thread.

2020-11-10 21:02 UTC, chuehlien commented
> > Added some minor comments for typos/file renaming. Can approve the PR once those are addressed.
> 
> Thank you for reviewing. I made all the changes/fixes you noted.
> 
> Before we can merge we need to change the ERD into an object diagram. @chuehlien are you able to do this? I can review if so.

Thanks, @j-d-b ! I've updated the ERD into an object diagram and tagged you as a reviewer in PR https://github.com/usdot-jpo-ode/jpo-wzdx/pull/143

2020-11-10 21:03 UTC, chuehlien approved these changes

2020-11-10 21:45 UTC, chuehlien commented on create-feed/README.md
> +- The [LaneRestriction](/spec-content/objects/LaneRestriction.md) object describes restrictions for identified lanes.
Will do!

2020-11-11 02:17 UTC, merged